name: wechat_assets_picker
description: An assets picker in pure dart which looks like the one in WeChat, support multi asset pick from device.
version: 2.0.1
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: ">=2.8.1 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  assets_audio_player: "^1.6.3"
  extended_image: ">=0.8.0 <2.0.0"
  photo_manager: ">=0.5.2 <2.0.0"
  provider: "^4.1.2"
  video_player: ">=0.10.11 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
